name: LazleCore
main: net.lazlecraft.LazleCore.LazleCore
version: 2.0
description: Basic Info commands for LazleCraft
website: http://LazleCraft.net
author: LaxWasHere
commands:
    lazlecraft:
        description: Shows icon menu.
    laxwashere:
        description: Because he was never here.
    server:
        description: choose a server.
    walls:
        description: Choose a walls server.